Repository nanego/my-dcim, pull requests merged in 2024-06, with the labels that each got.

#187 Fix i18n fallbacks configuration
  config/application.rb
  config/environments/production.rb
Labels: bug, i18n

#188 Make User settings has a default value by using store_atribute
  Gemfile
  Gemfile.lock
  app/models/application_record.rb
  app/models/user.rb
Labels: bug, enhancement

#190 Add missing filtered link to modeles on Category index
  app/views/categories/index.html.erb
Labels: enhancement

#141 Cleanup existing migrations
  .github/workflows/tests.yml
  db/migrate/20160224155811_create_composants.rb
  db/migrate/20160302133633_create_cards.rb
  db/migrate/20160311164516_rename_category_column.rb
  db/migrate/20160630173416_create_server_states.rb
  db/migrate/20160908123002_create_bay_types.rb
  db/migrate/20180110152701_add_attributes_to_servers.rb
  db/migrate/20190214134210_create_stacks.rb
Labels: enhancement

#191 Room#show: infinite JS load while showing a bay
  app/views/rooms/show.html.erb
Labels: bug

#194 Remove unused modal to add Server element in frame
  app/views/bays/show.html.erb
  app/views/frames/network.html.erb
  app/views/frames/show.html.erb
  app/views/rooms/show.html.erb
  app/views/servers/_modal_add_element_in_frame.html.erb
  config/locales/fr.yml
Labels: enhancement

#193 315747 - Use correct method to show card name in ConnectionsController#index
  app/views/connections/index.html.erb
Labels: bug
