Repository nanego/my-dcim, pull requests merged in 2024-09, with the labels that each got.

#199 Improve tests
  db/migrate/20240207105808_update_network_attribute.rb
  spec/components/filter_component_spec.rb
  spec/features/rooms/browse_room_spec.rb
  spec/requests/cables_request_spec.rb
  spec/requests/changelog_entries_spec.rb
  spec/requests/users_request_spec.rb
  test/controllers/bays_controller_test.rb
  test/controllers/frames_controller_test.rb
  test/fixtures/bays.yml
  test/fixtures/cards.yml
  test/fixtures/frames.yml
  test/fixtures/islets.yml
  test/fixtures/servers.yml
Labels: enhancement, quality

#202 340750 add islets in visualization dropdown
  app/views/layouts/navigation/_inventories_dropdown.html.erb
  app/views/layouts/navigation/_visualization_dropdown.html.erb
  app/views/rooms/show.html.erb
Labels: enhancement, i18n

#214 Fixing tests
  app/controllers/external_app_records_controller.rb
  app/controllers/external_app_requests_controller.rb
  app/jobs/sync_with_glpi_job.rb
  app/models/external_app_record.rb
  app/models/external_app_request.rb
  app/models/filter.rb
  app/services/glpi_client.rb
  app/views/layouts/navigation/_visualization_dropdown.html.erb
  db/migrate/20240822135649_create_external_app_requests.rb
  lib/tasks/sync_glpi_data.rake
  spec/controllers/external_app_records_controller_spec.rb
  spec/controllers/external_app_requests_controller_spec.rb
  spec/jobs/sync_with_glpi_job_spec.rb
  spec/jobs/sync_with_glpi_jop_spec.rb
  spec/models/external_app_request_spec.rb
  spec/requests/external_app_records_request_spec.rb
  spec/requests/external_app_requests_request_spec.rb
  spec/requests/islets_request_spec.rb
  spec/support/capybara.rb
  test/controllers/external_app_records_controller_test.rb
  test/fixtures/external_app_records.yml
  test/fixtures/external_app_requests.yml
  test/fixtures/users.yml
  test/jobs/sync_with_glpi_job_test.rb
Labels: enhancement

#213 Improving and fixing js on infrastructure page
  app/assets/stylesheets/application.scss
  app/views/islets/_infrastructure.html.erb
  app/views/visualization/infrastructures/show.html.erb
Labels: bug, enhancement

#216 Make Visualization controllers hide sidebar by default
  app/controllers/visualization/base_controller.rb
  app/controllers/visualization/infrastructures_controller.rb
  app/controllers/visualization/network_capacities_controller.rb
  app/views/visualization/infrastructures/show.html.erb
  app/views/visualization/network_capacities/show.html.erb
Labels: enhancement

#205 341626 - Move Rooms, Frames and Bays #show in a new namespaced controller
  app/controllers/bays_controller.rb
  app/controllers/frames_controller.rb
  app/controllers/islets_controller.rb
  app/controllers/rooms_controller.rb
  app/controllers/visualization/bays_controller.rb
  app/controllers/visualization/frames_controller.rb
  app/controllers/visualization/rooms_controller.rb
  app/views/bays/_export_button.html.erb
  app/views/bays/_overview.html.erb
  app/views/bays/edit.html.erb
  app/views/bays/index.html.erb
  app/views/bays/show.html.erb
  app/views/frames/edit.html.erb
  app/views/frames/index.html.erb
  app/views/frames/show.html.erb
  app/views/islets/_infrastructure.html.erb
  app/views/islets/_network_capacity.html.erb
  app/views/layouts/navigation/_visualization_dropdown.html.erb
  app/views/rooms/_action_buttons.html.erb
  app/views/rooms/_export_button.html.erb
  app/views/rooms/_room_overview.html.erb
  app/views/rooms/edit.html.erb
  app/views/rooms/index.html.erb
  app/views/rooms/show.html.erb
  app/views/visualization/bays/show.html.erb
  app/views/visualization/bays/show.js.erb
  app/views/visualization/frames/print.html.erb
  app/views/visualization/frames/show.html.erb
  app/views/visualization/frames/show.js.erb
  app/views/visualization/rooms/print.html.erb
  app/views/visualization/rooms/show.html.erb
  config/locales/fr.yml
  config/routes.rb
  spec/features/rooms/browse_room_spec.rb
  spec/requests/bays_request_spec.rb
  spec/requests/frames_request_spec.rb
  spec/requests/rooms_request_spec.rb
  test/integration/rooms_test.rb
Labels: enhancement
