Repository nanego/my-dcim, pull requests merged in 2024-01, with the labels that each got.

#126 Ruby 3.2
  .github/workflows/tests.yml
  .ruby-version
  Gemfile
  Gemfile.lock
  README.md
Labels: dependencies

#124 Update dependencies
  Gemfile.lock
Labels: dependencies

#117 Create DataTableComponent
  Gemfile
  Gemfile.lock
  app/components/list/data_table_component.rb
  app/components/list/table_component.rb
  app/controllers/application_controller.rb
  app/controllers/card_types_controller.rb
  app/controllers/clusters_controller.rb
  app/controllers/colors_controller.rb
  app/controllers/memory_types_controller.rb
  app/views/card_types/index.html.erb
  app/views/clusters/index.html.erb
  app/views/colors/index.html.erb
  app/views/memory_types/index.html.erb
  config/initializers/view_component.rb
  config/routes.rb
  spec/components/list/datatable_component_spec.rb
  spec/components/list/table_component_spec.rb
  spec/components/previews/layouts/component_preview.html.erb
  spec/components/previews/list/data_table_component_preview.rb
  spec/components/previews/list/data_table_component_preview/default.html.erb
  spec/components/previews/list/table_component_preview.rb
  spec/components/previews/list/table_component_preview/default.html.erb
Labels: enhancement

#130 Remove administrate dependency
  Gemfile
  Gemfile.lock
  app/controllers/admin/application_controller.rb
  app/dashboards/dashboard_manifest.rb
  config/routes.rb
Labels: enhancement, dependencies

#133 Refacto form error message into Component
  app/components/form_errors_component.rb
  app/views/architectures/_form.html.erb
  app/views/bays/_form.html.erb
  app/views/card_types/_form.html.erb
  app/views/card_types/index.html.erb
  app/views/categories/_form.html.erb
  app/views/clusters/_form.html.erb
  app/views/colors/_form.html.erb
  app/views/contract_types/_form.html.erb
  app/views/disk_types/_form.html.erb
  app/views/domaines/_form.html.erb
  app/views/frames/_form.html.erb
  app/views/gestions/_form.html.erb
  app/views/islets/_form.html.erb
  app/views/maintainers/_form.html.erb
  app/views/maintenance_contracts/_form.html.erb
  app/views/manufacturers/_form.html.erb
  app/views/memory_types/_form.html.erb
  app/views/modeles/_form.html.erb
  app/views/modeles/edit.html.erb
  app/views/port_types/_form.html.erb
  app/views/rooms/_form.html.erb
  app/views/servers/_form.html.erb
  app/views/servers/_modal_add_element_in_frame.html.erb
  app/views/sites/_form.html.erb
  app/views/stacks/_form.html.erb
  app/views/users/new.html.erb
  config/locales/components.en.yml
  config/locales/components.fr.yml
  config/locales/fr.yml
  spec/components/form_errors_component_spec.rb
  spec/components/previews/form_errors_component_preview.rb
  spec/components/previews/layouts/component_preview.html.erb
Labels: enhancement

#136 security: filter sensitive data in ChangelogEntry#object_changed_attributes
  app/models/changelog_entry.rb
  app/models/concerns/changelogable.rb
Labels: security
