Repository nanego/my-dcim, pull requests merged in 2024-11, with the labels that each got.

#246 341632 Add Lift pump attribute to AirConditioner
  app/controllers/air_conditioners_controller.rb
  app/views/air_conditioners/_form.html.erb
  app/views/air_conditioners/show.html.erb
  config/locales/activerecord.fr.yml
  db/migrate/20241030101913_add_lift_pump_attribute_to_air_conditioner.rb
  db/schema.rb
Labels: enhancement

#248 343753 Improve card form on Server#form
  app/assets/stylesheets/application.scss
  app/models/card.rb
  app/views/modeles/_form.html.erb
  app/views/servers/_card_fields.html.erb
  app/views/servers/_form.html.erb
  config/locales/activerecord.fr.yml
  spec/models/card_spec.rb
Labels: enhancement

#234 343808 - Add presence and format validation on Card name
  app/models/composant.rb
  app/views/modeles/_enclosure_fields.html.erb
  config/locales/activerecord.fr.yml
  spec/models/composant_spec.rb
Labels: enhancement

#245 341631 Add width to Frame
  app/controllers/frames_controller.rb
  app/helpers/application_helper.rb
  app/views/frames/_form.html.erb
  app/views/frames/show.html.erb
  config/locales/activerecord.fr.yml
  config/locales/fr.yml
  db/migrate/20241030094252_add_width_attribute_to_frames.rb
  db/schema.rb
Labels: enhancement

#250 #236 - Better Localization sections
  app/views/air_conditioners/show.html.erb
  app/views/bays/show.html.erb
  app/views/frames/show.html.erb
  app/views/islets/show.html.erb
  app/views/rooms/_form.html.erb
  app/views/rooms/show.html.erb
  app/views/servers/_card_fields.html.erb
  app/views/servers/_form.html.erb
  app/views/servers/show.html.erb
  app/views/sites/_form.html.erb
  app/views/sites/show.html.erb
  config/locales/activerecord.fr.yml
Labels: enhancement

#257 239 verify newedit form submit redirections
  app/components/form/actions_component.rb
  app/components/page/heading_edit_component.rb
  app/components/page/heading_new_component.rb
  app/components/page/heading_show_component.rb
  app/controllers/card_types_controller.rb
  app/controllers/stacks_controller.rb
  app/models/card_type.rb
  app/views/air_conditioners/_form.html.erb
  app/views/architectures/_form.html.erb
  app/views/bays/_form.html.erb
  app/views/card_types/_form.html.erb
  app/views/categories/_form.html.erb
  app/views/clusters/_form.html.erb
  app/views/colors/_form.html.erb
  app/views/contract_types/_form.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/disk_types/_form.html.erb
  app/views/domaines/_form.html.erb
  app/views/frames/_form.html.erb
  app/views/gestions/_form.html.erb
  app/views/islets/_form.html.erb
  app/views/maintainers/_form.html.erb
  app/views/manufacturers/_form.html.erb
  app/views/memory_types/_form.html.erb
  app/views/modeles/_form.html.erb
  app/views/moves/_form.html.erb
  app/views/port_types/_form.html.erb
  app/views/rooms/_form.html.erb
  app/views/servers/_form.html.erb
  app/views/sites/_form.html.erb
  app/views/stacks/_form.html.erb
  app/views/users/new.html.erb
  app/views/users/settings/edit.html.erb
  config/locales/fr.yml
  spec/components/form/actions_component_spec.rb
  spec/requests/card_types_request_spec.rb
  spec/requests/stacks_request_spec.rb
  spec/support/view_component.rb
  test/controllers/card_types_controller_test.rb
  test/controllers/stacks_controller_test.rb
Labels: bug, enhancement

#258 352641 add move cta on server show
  app/components/button_component.rb
  app/components/page/heading_edit_component.rb
  app/components/page/heading_new_component.rb
  app/components/page/heading_show_component.rb
  app/controllers/moves_controller.rb
  app/views/changelog_entries/show.html.erb
  app/views/moves/frame.html.erb
  app/views/servers/import_csv.html.erb
  app/views/servers/show.html.erb
  config/locales/fr.yml
  spec/components/button_component_spec.rb
  spec/components/page/heading_edit_component_spec.rb
  spec/components/page/heading_new_component_spec.rb
  spec/components/page/heading_show_component_spec.rb
  spec/requests/moves_request_spec.rb
  test/controllers/moves_controller_test.rb
Labels: enhancement

#256 Add warning icon on bay if it has no frame associated
  app/decorators/bay_decorator.rb
  app/views/bays/index.html.erb
  app/views/bays/show.html.erb
  config/locales/fr.yml
  spec/decorators/bay_decorator_spec.rb
Labels: enhancement

#244 341629 Add new attributes (width/depth/manufacturer) to Bay
  app/controllers/bays_controller.rb
  app/helpers/application_helper.rb
  app/models/bay.rb
  app/models/manufacturer.rb
  app/processors/bays_processor.rb
  app/views/bays/_form.html.erb
  app/views/bays/index.html.erb
  app/views/bays/show.html.erb
  app/views/frames/show.html.erb
  app/views/manufacturers/index.html.erb
  app/views/manufacturers/show.html.erb
  app/views/rooms/_form.html.erb
  app/views/rooms/show.html.erb
  config/locales/activerecord.fr.yml
  config/locales/fr.yml
  db/migrate/20241029164923_add_new_attributes_to_bay.rb
  db/migrate/20241106103902_add_bay_counter_cache_to_manufacturer.rb
  db/schema.rb
  spec/helpers/application_helper_spec.rb
  spec/models/bay_spec.rb
  spec/models/manufacturer_spec.rb
  spec/processors/bays_processor_spec.rb
Labels: enhancement

#243 341621 Add attribute access control to Room, Islet and Bay
  app/controllers/bays_controller.rb
  app/controllers/islets_controller.rb
  app/controllers/rooms_controller.rb
  app/decorators/bay_decorator.rb
  app/decorators/islet_decorator.rb
  app/decorators/room_decorator.rb
  app/models/bay.rb
  app/models/islet.rb
  app/models/room.rb
  app/views/bays/_form.html.erb
  app/views/bays/show.html.erb
  app/views/islets/_form.html.erb
  app/views/islets/show.html.erb
  app/views/rooms/_form.html.erb
  app/views/rooms/show.html.erb
  config/locales/activerecord.fr.yml
  config/locales/fr.yml
  db/migrate/20241029145546_add_attribute_access_control_to_room_islet_bay.rb
  db/schema.rb
  spec/decorators/bay_decorator_spec.rb
  spec/decorators/islet_decorator_spec.rb
  spec/decorators/room_decorator_spec.rb
  spec/models/bay_spec.rb
  spec/models/islet_spec.rb
  spec/models/room_spec.rb
Labels: enhancement

#259 353217 API: Fix search by name on server
  app/controllers/servers_controller.rb
Labels: bug

#251 237 small indexes improvments
  app/decorators/external_app_record_decorator.rb
  app/views/air_conditioners/index.html.erb
  app/views/architectures/index.html.erb
  app/views/bays/index.html.erb
  app/views/card_types/index.html.erb
  app/views/categories/index.html.erb
  app/views/clusters/index.html.erb
  app/views/colors/index.html.erb
  app/views/contract_types/index.html.erb
  app/views/external_app_records/index.html.erb
  app/views/gestions/index.html.erb
  app/views/islets/index.html.erb
  app/views/maintainers/index.html.erb
  app/views/manufacturers/index.html.erb
  app/views/memory_types/index.html.erb
  app/views/moves/index.html.erb
  app/views/stacks/index.html.erb
  config/locales/activerecord.fr.yml
  config/routes.rb
  spec/decorators/external_app_record_decorator_spec.rb
Labels: enhancement

#264 Make filters with association select being multiple
  app/processors/air_conditioners_processor.rb
  app/processors/bays_processor.rb
  app/processors/contact_assignments_processor.rb
  app/processors/frames_processor.rb
  app/processors/islets_processor.rb
  app/processors/modeles_processor.rb
  app/processors/rooms_processor.rb
  app/views/air_conditioners/index.html.erb
  app/views/architectures/index.html.erb
  app/views/architectures/show.html.erb
  app/views/bays/index.html.erb
  app/views/bays/show.html.erb
  app/views/categories/index.html.erb
  app/views/categories/show.html.erb
  app/views/contact_assignments/index.html.erb
  app/views/contacts/show.html.erb
  app/views/frames/index.html.erb
  app/views/islets/index.html.erb
  app/views/islets/show.html.erb
  app/views/manufacturers/index.html.erb
  app/views/manufacturers/show.html.erb
  app/views/modeles/index.html.erb
  app/views/rooms/index.html.erb
  app/views/rooms/show.html.erb
  app/views/servers/index.html.erb
  app/views/sites/index.html.erb
  app/views/sites/show.html.erb
  config/locales/fr.yml
  spec/processors/air_conditioners_processor_spec.rb
  spec/processors/bays_processor_spec.rb
  spec/processors/contact_assignments_processor_spec.rb
  spec/processors/frames_processor_spec.rb
  spec/processors/islets_processor_spec.rb
  spec/processors/modeles_processor_spec.rb
  spec/processors/rooms_processor_spec.rb
  spec/processors/servers_processor_spec.rb
Labels: enhancement

#266 Improve Headers design
  app/assets/stylesheets/application.scss
  app/components/button_component.rb
  app/components/page/heading_component.rb
  app/components/page/heading_edit_component.rb
  app/components/page/heading_new_component.rb
  app/components/page/heading_show_component.rb
  app/views/changelog_entries/show.html.erb
  app/views/connections/edit.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/external_app_records/index.html.erb
  app/views/moves/frame.html.erb
  app/views/servers/import_csv.html.erb
  app/views/users/index.html.erb
  app/views/users/settings/edit.html.erb
  app/views/users/show.html.erb
  spec/components/button_component_spec.rb
  spec/components/page/heading_component_spec.rb
  spec/components/page/heading_edit_component_spec.rb
  spec/components/page/heading_new_component_spec.rb
  spec/components/page/heading_show_component_spec.rb
Labels: enhancement

#270 Fixing Search bar position on mobile
  app/assets/stylesheets/application.scss
  app/views/layouts/_header.html.erb
  app/views/search/_search_field.html.erb
Labels: bug, enhancement

#273 Fix port type index
  app/controllers/card_types_controller.rb
  app/models/port_type.rb
  app/processors/card_types_processor.rb
  app/views/card_types/index.html.erb
  app/views/port_types/index.html.erb
  config/locales/fr.yml
  spec/processors/card_types_processor_spec.rb
  spec/requests/card_types_request_spec.rb
Labels: bug, enhancement

#274 342607 Remove maintainance tables
  .rubocop_todo.yml
  app/controllers/contract_types_controller.rb
  app/controllers/maintainers_controller.rb
  app/controllers/maintenance_contracts_controller.rb
  app/helpers/contract_types_helper.rb
  app/helpers/maintainers_helper.rb
  app/models/contract_type.rb
  app/models/maintainer.rb
  app/models/maintenance_contract.rb
  app/models/server.rb
  app/views/contract_types/_contract_type.json.jbuilder
  app/views/contract_types/_form.html.erb
  app/views/contract_types/edit.html.erb
  app/views/contract_types/index.html.erb
  app/views/contract_types/index.json.jbuilder
  app/views/contract_types/new.html.erb
  app/views/contract_types/show.html.erb
  app/views/contract_types/show.json.jbuilder
  app/views/layouts/_sidebar.html.erb
  app/views/maintainers/_form.html.erb
  app/views/maintainers/_maintainer.json.jbuilder
  app/views/maintainers/edit.html.erb
  app/views/maintainers/index.html.erb
  app/views/maintainers/index.json.jbuilder
  app/views/maintainers/new.html.erb
  app/views/maintainers/show.html.erb
  app/views/maintainers/show.json.jbuilder
  app/views/maintenance_contracts/_form.html.erb
  app/views/maintenance_contracts/_maintenance_contract.json.jbuilder
  app/views/maintenance_contracts/edit.html.erb
  app/views/maintenance_contracts/index.html.erb
  app/views/maintenance_contracts/index.json.jbuilder
  app/views/maintenance_contracts/new.html.erb
  app/views/maintenance_contracts/show.html.erb
  app/views/maintenance_contracts/show.json.jbuilder
  config/locales/activerecord.fr.yml
  config/locales/fr.yml
  config/routes.rb
  db/migrate/20241127144521_drop_maintaince_related_tables.rb
  db/schema.rb
  spec/models/contract_type_spec.rb
  spec/models/maintainer_spec.rb
  spec/models/maintenance_contract_spec.rb
  spec/models/server_spec.rb
  test/controllers/contract_types_controller_test.rb
  test/controllers/maintainers_controller_test.rb
  test/controllers/maintenance_contracts_controller_test.rb
  test/fixtures/contract_types.yml
  test/fixtures/maintainers.yml
  test/fixtures/maintenance_contracts.yml
  test/models/contract_type_test.rb
  test/models/maintainer_test.rb
  test/models/maintenance_contract_test.rb
Labels: enhancement

#262 343823 Add filters to the GLPI synchronization page
  app/assets/stylesheets/application.scss
  app/controllers/external_app_records_controller.rb
  app/decorators/external_app_record_decorator.rb
  app/models/external_app_record.rb
  app/processors/external_app_records_processor.rb
  app/views/external_app_records/index.html.erb
  app/views/servers/index.html.erb
  config/locales/activerecord.fr.yml
  config/locales/fr.yml
  spec/decorators/external_app_record_decorator_spec.rb
  spec/models/external_app_record_spec.rb
  spec/models/external_app_request_spec.rb
  spec/processors/external_app_records_processor_spec.rb
  spec/requests/external_app_records_request_spec.rb
  test/fixtures/external_app_records.yml
Labels: enhancement
