Repository nanego/my-dcim, pull requests merged in 2024-02, with the labels that each got.

#129 287580 - Datatable sort
  app/controllers/architectures_controller.rb
  app/controllers/bays_controller.rb
  app/controllers/categories_controller.rb
  app/controllers/contract_types_controller.rb
  app/controllers/disk_types_controller.rb
  app/controllers/domaines_controller.rb
  app/controllers/frames_controller.rb
  app/controllers/gestions_controller.rb
  app/controllers/islets_controller.rb
  app/controllers/maintainers_controller.rb
  app/controllers/manufacturers_controller.rb
  app/controllers/modeles_controller.rb
  app/controllers/port_types_controller.rb
  app/controllers/rooms_controller.rb
  app/controllers/sites_controller.rb
  app/controllers/stacks_controller.rb
  app/views/architectures/index.html.erb
  app/views/bays/index.html.erb
  app/views/card_types/_form.html.erb
  app/views/card_types/index.html.erb
  app/views/card_types/show.html.erb
  app/views/categories/index.html.erb
  app/views/clusters/index.html.erb
  app/views/contract_types/index.html.erb
  app/views/disk_types/index.html.erb
  app/views/domaines/index.html.erb
  app/views/frames/index.html.erb
  app/views/gestions/index.html.erb
  app/views/islets/index.html.erb
  app/views/maintainers/index.html.erb
  app/views/manufacturers/index.html.erb
  app/views/modeles/index.html.erb
  app/views/port_types/index.html.erb
  app/views/rooms/index.html.erb
  app/views/servers/index.html.erb
  app/views/sites/index.html.erb
  app/views/stacks/index.html.erb
  config/locales/activerecord.fr.yml
  config/locales/fr.yml
Labels: enhancement

#140 Missings tranlations
  app/models/servers_grid.rb
  app/views/modeles/_composant_alim_fields.html.erb
  app/views/moves/frame.html.erb
  app/views/ports/_form.html.erb
  vendor/assets/sortablejs/sortable.js
Labels: enhancement, i18n

#137 Add counter cache
  app/assets/stylesheets/application.css.scss
  app/components/list/table_component.rb
  app/controllers/bays_controller.rb
  app/controllers/disk_types_controller.rb
  app/controllers/frames_controller.rb
  app/controllers/islets_controller.rb
  app/controllers/servers_controller.rb
  app/models/card_type.rb
  app/models/modele.rb
  app/models/room.rb
  app/models/server.rb
  app/views/architectures/index.html.erb
  app/views/bays/index.html.erb
  app/views/card_types/index.html.erb
  app/views/categories/index.html.erb
  app/views/clusters/index.html.erb
  app/views/disk_types/index.html.erb
  app/views/domaines/index.html.erb
  app/views/frames/index.html.erb
  app/views/gestions/index.html.erb
  app/views/islets/index.html.erb
  app/views/manufacturers/index.html.erb
  app/views/modeles/index.html.erb
  app/views/port_types/index.html.erb
  app/views/rooms/index.html.erb
  app/views/servers/index.html.erb
  app/views/sites/index.html.erb
  app/views/stacks/index.html.erb
  db/migrate/20240207105229_add_counter_caches.rb
  db/schema.rb
  spec/requests/servers_request_spec.rb
  test/fixtures/architectures.yml
  test/fixtures/categories.yml
  test/fixtures/clusters.yml
  test/fixtures/domaines.yml
  test/fixtures/gestions.yml
  test/fixtures/manufacturers.yml
  test/fixtures/stacks.yml
Labels: enhancement

#131 300857 — Improve ChangelogEntry index page
  .github/workflows/tests.yml
  app/controllers/changelog_entries_controller.rb
  app/models/changelog_entry.rb
  app/models/concerns/changelogable.rb
  app/models/user.rb
  app/views/changelog_entries/index.html.erb
  app/views/changelog_entries/show.html.erb
  app/views/users/show.html.erb
  config/locales/activerecord.fr.yml
Labels: enhancement

#145 307237 - add more link to references on server show page
  app/views/servers/show.html.erb
Labels: enhancement

#148 Fix translation use for Modele.manufacturer
  config/locales/activerecord.fr.yml
Labels: bug, i18n

#150 Bump ruby to 3.2.3
  .github/workflows/tests.yml
  .ruby-version
  Gemfile
  Gemfile.lock
Labels: dependencies, security

#151 Fix: don't use user#authentication_token.length for hidden value
  app/views/users/show.html.erb
Labels: bug
