Repository nanego/my-dcim, pull requests merged in 2024-12, with the labels that each got.

#278 356065 move position attribute to localization on server pages
  app/views/servers/_form.html.erb
  app/views/servers/show.html.erb
Labels: enhancement

#280 279 update scaffold to use heading components
  app/views/architectures/index.html.erb
  app/views/architectures/show.html.erb
  lib/templates/erb/scaffold/_form.html.erb
  lib/templates/erb/scaffold/edit.html.erb
  lib/templates/erb/scaffold/index.html.erb
  lib/templates/erb/scaffold/new.html.erb
  lib/templates/erb/scaffold/show.html.erb
Labels: enhancement

#272 Harmonize Edit button color on Assignment block on site#show
  app/views/sites/show.html.erb
Labels: enhancement

#282 Fix not found filter on external app records
  app/controllers/external_app_records_controller.rb
  app/processors/external_app_records_processor.rb
  app/views/external_app_records/index.html.erb
  spec/processors/external_app_records_processor_spec.rb
  test/fixtures/external_app_records.yml
Labels: bug

#285 357031 — fix: add missing attribute in ContactProcessor::SORTABLE_FIELDS
  app/processors/contacts_processor.rb
Labels: bug

#275 343816 add button to delete connection on server show
  app/assets/stylesheets/application.scss
  app/components/button_component.rb
  app/controllers/connections_controller.rb
  app/controllers/servers_controller.rb
  app/models/server.rb
  app/processors/connections_processor.rb
  app/views/connections/index.html.erb
  app/views/connections/update.js.erb
  app/views/ports/_modal_edit_port.html.erb
  app/views/servers/show.html.erb
  config/locales/fr.yml
  config/routes.rb
  spec/models/server_spec.rb
  spec/processors/connections_processor_spec.rb
  spec/requests/connections_request_spec.rb
  spec/requests/servers_request_spec.rb
  test/fixtures/cables.yml
  test/fixtures/connections.yml
  test/fixtures/ports.yml
Labels: enhancement

#286 clean: remove ActiveRecord::Normalization backport
  app/models/application_record.rb
  app/models/concerns/active_record/normalization.rb
Labels: quality

#288 Show different flash message when SeversController#destroy fail
  app/controllers/servers_controller.rb
  config/locales/fr.yml
Labels: enhancement

#299 Change default items per page from 50 to 100
  Gemfile.lock
  config/initializers/pagy.rb
Labels: enhancement

#287 351548 - add filters on ExternalAppRecord sync with Category
  app/controllers/categories_controller.rb
  app/controllers/external_app_records_controller.rb
  app/jobs/sync_with_glpi_job.rb
  app/models/category.rb
  app/models/external_app_record.rb
  app/models/modele.rb
  app/models/server.rb
  app/processors/categories_processor.rb
  app/views/categories/_form.html.erb
  app/views/categories/index.html.erb
  app/views/categories/index.json.jbuilder
  app/views/categories/show.html.erb
  app/views/categories/show.json.jbuilder
  app/views/external_app_records/index.html.erb
  config/application.rb
  config/locales/activerecord.fr.yml
  db/migrate/20241204143353_add_is_glpi_synchronizable_to_categories.rb
  db/schema.rb
  lib/tasks/sync_glpi_data.rake
  spec/models/external_app_record_spec.rb
  spec/models/modele_spec.rb
  spec/models/server_spec.rb
  spec/processors/categories_processor_spec.rb
  test/fixtures/categories.yml
  test/jobs/sync_with_glpi_job_test.rb
Labels: enhancement

#295 358557 - Fix document deleted on server
  app/javascript/controllers/nested_form_controller.js
Labels: bug

#293 358558 - Add locales to controllers flash message
  app/controllers/cables_controller.rb
  app/controllers/connections_controller.rb
  app/controllers/disks_controller.rb
  app/controllers/documents_controller.rb
  app/controllers/memory_components_controller.rb
  app/controllers/modeles_controller.rb
  app/controllers/moves_controller.rb
  app/controllers/ports_controller.rb
  app/controllers/rooms_controller.rb
  app/controllers/server_states_controller.rb
  app/controllers/servers_controller.rb
  config/locales/fr.yml
Labels: enhancement

#291 343818 Improve Display input on Enclosure fields form
  app/assets/stylesheets/application.scss
  app/controllers/modeles_controller.rb
  app/decorators/modele_decorator.rb
  app/javascript/controllers/enclosure_fields_controller.js
  app/javascript/src/index.js
  app/models/composant.rb
  app/models/enclosure.rb
  app/models/modele.rb
  app/views/islets/_network_capacity.html.erb
  app/views/modeles/_composant_fields.html.erb
  app/views/modeles/_enclosure_fields.html.erb
  app/views/modeles/_form.html.erb
  app/views/modeles/index.html.erb
  app/views/modeles/preview.turbo_stream.erb
  app/views/pdus/_pdu.html.erb
  app/views/servers/_card_fields.html.erb
  app/views/servers/_draw_patch_panel.html.erb
  app/views/servers/_draw_server.html.erb
  app/views/servers/_draw_server_compact.html.erb
  app/views/servers/_form.html.erb
  app/views/servers/show.html.erb
  config/locales/activerecord.fr.yml
  config/locales/en.yml
  config/locales/fr.yml
  spec/decorators/modele_decorator_spec.rb
  spec/models/enclosure_spec.rb
  spec/requests/modeles_request_spec.rb
  test/controllers/modeles_controller_test.rb
Labels: enhancement

#303 Add settings page to GLPI sync
  app/controllers/external_app_records_controller.rb
  app/models/external_app_record_setting.rb
  app/views/external_app_records/index.html.erb
  app/views/external_app_records/settings.html.erb
  app/views/servers/index.html.erb
  config/locales/fr.yml
  config/routes.rb
  spec/models/external_app_record_setting_spec.rb
  spec/requests/external_app_records_request_spec.rb
Labels: enhancement

#308 Fix Grid preview display on modele preview + add preview on show
  app/views/modeles/_visualization.html.erb
  app/views/modeles/preview.turbo_stream.erb
  app/views/modeles/show.html.erb
  config/locales/fr.yml
Labels: bug, enhancement
