Repository nanego/my-dcim, pull requests merged in 2024-10, with the labels that each got.

#217 342566 - Remove public_activity gem
  Gemfile
  Gemfile.lock
  app/controllers/activities_controller.rb
  app/controllers/application_controller.rb
  app/controllers/servers_controller.rb
  app/helpers/activities_helper.rb
  app/models/architecture.rb
  app/models/card.rb
  app/models/card_type.rb
  app/models/category.rb
  app/models/cluster.rb
  app/models/color.rb
  app/models/composant.rb
  app/models/domaine.rb
  app/models/frame.rb
  app/models/gestion.rb
  app/models/manufacturer.rb
  app/models/modele.rb
  app/models/port.rb
  app/models/port_type.rb
  app/models/room.rb
  app/models/server.rb
  app/models/type_composant.rb
  app/models/user.rb
  app/views/activities/index.html.erb
  app/views/layouts/navigation/_nav_links_administration.html.erb
  app/views/public_activity/_default.html.erb
  app/views/public_activity/serveur/_create.html.erb
  app/views/public_activity/serveur/_destroy.html.erb
  app/views/public_activity/serveur/_update.html.erb
  app/views/public_activity/user/_create.html.erb
  app/views/public_activity/user/_update.html.erb
  config/application.rb
  config/locales/fr.yml
  config/routes.rb
  db/migrate/20160908123000_update_renamed_classes_in_activities.rb
  db/migrate/20170628134311_replace_renamed_classes_in_activities.rb
  db/migrate/20240918141423_drop_public_activities.rb
  db/schema.rb
  test/controllers/activities_controller_test.rb
  test/controllers/application_controller_test.rb
Labels: enhancement

#223 Update dependencies
  Gemfile.lock
  app/javascript/controllers/export_pdf_controller.js
  vendor/javascript/html2pdf.js.bundle.js
  yarn.lock
Labels: dependencies

#210 341617 - Add ChangelogEntry to show pages
  Gemfile.lock
  app/components/ChangelogEntries/object_list_component.rb
  app/controllers/changelog_entries_controller.rb
  app/views/air_conditioners/show.html.erb
  app/views/architectures/show.html.erb
  app/views/bays/show.html.erb
  app/views/card_types/show.html.erb
  app/views/categories/show.html.erb
  app/views/changelog_entries/index.html.erb
  app/views/clusters/show.html.erb
  app/views/colors/show.html.erb
  app/views/contract_types/show.html.erb
  app/views/disk_types/show.html.erb
  app/views/domaines/show.html.erb
  app/views/frames/show.html.erb
  app/views/gestions/show.html.erb
  app/views/islets/show.html.erb
  app/views/maintainers/show.html.erb
  app/views/manufacturers/show.html.erb
  app/views/memory_types/show.html.erb
  app/views/modeles/show.html.erb
  app/views/port_types/show.html.erb
  app/views/rooms/show.html.erb
  app/views/servers/show.html.erb
  app/views/sites/show.html.erb
  app/views/stacks/show.html.erb
  config/locales/components.en.yml
  config/locales/components.fr.yml
  config/routes.rb
  spec/components/changelog_entries/object_list_component_spec.rb
Labels: enhancement

#215 341610 - Add child block table on #show
  app/assets/stylesheets/application.scss
  app/components/has_many_turbo_frame_component.rb
  app/controllers/islets_controller.rb
  app/processors/frames_processor.rb
  app/views/bays/_export_button.html.erb
  app/views/bays/index.html.erb
  app/views/bays/show.html.erb
  app/views/frames/index.html.erb
  app/views/frames/show.html.erb
  app/views/islets/_export_button.html.erb
  app/views/islets/index.html.erb
  app/views/islets/show.html.erb
  app/views/rooms/_export_button.html.erb
  app/views/rooms/index.html.erb
  app/views/rooms/show.html.erb
  app/views/servers/index.html.erb
  app/views/sites/show.html.erb
  config/locales/components.en.yml
  config/locales/components.fr.yml
  config/locales/fr.yml
  spec/components/has_many_turbo_frame_component_spec.rb
  spec/components/previews/has_many_turbo_frame_component_preview.rb
Labels: enhancement

#225 add Islet processor + update controller to use it
  app/controllers/islets_controller.rb
  app/processors/islets_processor.rb
  spec/processors/islets_processor_spec.rb
  spec/requests/islets_request_spec.rb
Labels: bug, enhancement

#222 343829 - Allow multiple values on filters
  app/assets/stylesheets/application.scss
  app/components/filter_component.rb
  app/models/filter.rb
  app/processors/application_processor.rb
  app/processors/servers_processor.rb
  app/views/bays/index.html.erb
  app/views/clusters/index.html.erb
  app/views/domaines/index.html.erb
  app/views/gestions/index.html.erb
  app/views/modeles/index.html.erb
  app/views/servers/index.html.erb
  config/locales/fr.yml
  spec/processors/servers_processor_spec.rb
Labels: enhancement

#227 Reorder filter inputs
  app/views/frames/index.html.erb
Labels: enhancement

#228 Update forgotten server filters links
  app/models/filter.rb
  app/views/frames/show.html.erb
  spec/components/previews/has_many_turbo_frame_component_preview.rb
Labels: bug

#247 Fixing empty value too small on FF (Tom-select inputs)
  app/assets/stylesheets/application.scss
Labels: bug
