Repository nanego/my-dcim, pull requests merged in 2024-05, with the labels that each got.

#179 Update connection indexes
  app/assets/stylesheets/application.css.scss
  app/controllers/connections_controller.rb
  app/models/connection.rb
  app/views/cables/index.html.erb
  app/views/connections/index.html.erb
  config/locales/activerecord.fr.yml
Labels: enhancement

#182 security: bump ruby to 3.3.1
  .github/workflows/tests.yml
  .rubocop.yml
  .ruby-version
  Gemfile
  Gemfile.lock
Labels: dependencies, security

#176 Fixing wrong network data migration
  app/assets/stylesheets/rooms.css.scss
  app/controllers/modeles_controller.rb
  app/controllers/rooms_controller.rb
  app/controllers/servers_controller.rb
  app/javascript/controllers/hello_controller.js
  app/models/application_record.rb
  app/models/concerns/active_record/normalization.rb
  app/models/modele.rb
  app/models/modele/network.rb
  app/models/server.rb
  app/views/modeles/_form.html.erb
  app/views/modeles/index.html.erb
  app/views/rooms/_infrastructure_islet.html.erb
  app/views/rooms/capacity.html.erb
  app/views/rooms/infrastructure.html.erb
  app/views/servers/_form.html.erb
  app/views/servers/index.html.erb
  app/views/servers/show.html.erb
  config/locales/activerecord.fr.yml
  config/locales/fr.yml
  db/migrate/20240207105808_update_network_attribute.rb
  db/schema.rb
  spec/models/modele_spec.rb
  spec/models/server_spec.rb
Labels: bug

#170 Filters system
  Gemfile
  Gemfile.lock
  app/components/filter_component.rb
  app/components/list/data_table_component.rb
  app/controllers/application_controller.rb
  app/controllers/bays_controller.rb
  app/controllers/clusters_controller.rb
  app/controllers/frames_controller.rb
  app/controllers/modeles_controller.rb
  app/controllers/rooms_controller.rb
  app/controllers/servers_controller.rb
  app/controllers/users_controller.rb
  app/models/filter.rb
  app/models/frame.rb
  app/models/modele.rb
  app/processors/application_processor.rb
  app/processors/bays_processor.rb
  app/processors/clusters_processor.rb
  app/processors/concerns/sortable.rb
  app/processors/frames_processor.rb
  app/processors/modeles_processor.rb
  app/processors/rooms_processor.rb
  app/processors/servers_processor.rb
  app/processors/users_processor.rb
  app/views/bays/index.html.erb
  app/views/clusters/index.html.erb
  app/views/frames/index.html.erb
  app/views/modeles/index.html.erb
  app/views/rooms/index.html.erb
  app/views/servers/index.html.erb
  app/views/sites/index.html.erb
  app/views/users/index.html.erb
  config/application.rb
  config/locales/components.fr.yml
  config/locales/fr.yml
  spec/components/filter_component_spec.rb
  spec/models/filter_spec.rb
  spec/processors/bays_processor_spec.rb
  spec/processors/clusters_processor_spec.rb
  spec/processors/frames_processor_spec.rb
  spec/processors/modeles_processor_spec.rb
  spec/processors/rooms_processor_spec.rb
  spec/processors/servers_processor_spec.rb
  spec/processors/users_processor_spec.rb
  spec/rails_helper.rb
  spec/requests/servers_request_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#181 320594 Store user settings
  app/controllers/application_controller.rb
  app/controllers/concerns/localization.rb
  app/controllers/users/settings_controller.rb
  app/decorators/user_decorator.rb
  app/models/user.rb
  app/views/layouts/_nav_links_administration.html.erb
  app/views/rooms/_action_buttons.html.erb
  app/views/rooms/show.html.erb
  app/views/users/settings/edit.html.erb
  config/application.rb
  config/locales/activerecord.en.yml
  config/locales/activerecord.fr.yml
  config/locales/en.yml
  config/locales/fr.yml
  config/routes.rb
  db/migrate/20240502093850_add_settings_to_users.rb
  db/schema.rb
  spec/decorators/user_decorator_spec.rb
  spec/models/user_spec.rb
  spec/requests/users/settings_request_spec.rb
Labels: enhancement
