Repository nanego/my-dcim, pull requests merged in 2025-09, with the labels that each got.

#479 fix: make select controller works with select without optgroup
  app/javascript/controllers/select_controller.js
Labels: bug

#473 392479 Manage remaining views with new policies
  app/controllers/changelog_entries_controller.rb
  app/policies/changelog_entry_policy.rb
  app/views/architectures/show.html.erb
  app/views/bays/show.html.erb
  app/views/categories/show.html.erb
  app/views/clusters/show.html.erb
  app/views/contacts/show.html.erb
  app/views/domaines/show.html.erb
  app/views/frames/show.html.erb
  app/views/gestions/show.html.erb
  app/views/islets/show.html.erb
  app/views/layouts/navigation/_nav_links_administration.html.erb
  app/views/manufacturers/show.html.erb
  app/views/modeles/show.html.erb
  app/views/rooms/_action_buttons.html.erb
  app/views/rooms/show.html.erb
  app/views/servers/show.html.erb
  app/views/sites/show.html.erb
  app/views/stacks/show.html.erb
  app/views/visualization/infrastructures/show.html.erb
  spec/policies/changelog_entry_policy_spec.rb
  spec/requests/changelog_entries_spec.rb
Labels: bug, enhancement

#484 Add constraints to gems on Gemfile
  Gemfile
  Gemfile.lock
Labels: dependencies
