Repository nanego/my-dcim, pull requests merged in 2025-06, with the labels that each got.

#411 Update moves to show bays after moves
  app/controllers/application_controller.rb
  app/controllers/moves_controller.rb
  app/controllers/moves_project_steps_controller.rb
  app/models/moved_connection.rb
  app/models/moves_project_step.rb
  app/views/moves/_frames.html.erb
  app/views/moves/index.html.erb
  app/views/moves_project_steps/frame.html.erb
  app/views/moves_project_steps/print.html.erb
  app/views/moves_projects/show.html.erb
  config/locales/fr.yml
  config/routes.rb
  spec/models/moves_project_step_spec.rb
  spec/requests/moves_controller_request_spec.rb
  spec/requests/moves_project_steps_controller_request_spec.rb
Labels: enhancement

#416 Update moves projet steps design
  app/components/card_component.rb
  app/controllers/moves_controller.rb
  app/decorators/move_decorator.rb
  app/javascript/controllers/frame_export_pdf_controller.js
  app/views/moves/edit.html.erb
  app/views/moves/index.html.erb
  app/views/moves_projects/show.html.erb
  config/locales/activerecord.en.yml
  config/locales/activerecord.fr.yml
  config/locales/en.yml
  config/locales/fr.yml
  spec/decorators/move_decorator_spec.rb
Labels: enhancement

#412 Improve global search
  app/controllers/search_controller.rb
  app/models/server.rb
  app/models/server_frame_view.rb
  app/views/search/index.html.erb
Labels: bug, enhancement

#420 Fix crash Project#show when created without steps
  app/components/card_empty_data_component.rb
  app/components/list/data_table_component.rb
  app/views/moves_projects/show.html.erb
  config/locales/components.en.yml
  config/locales/components.fr.yml
  spec/components/card_empty_data_component_spec.rb
  spec/components/previews/card_empty_data_component_preview.rb
Labels: bug

#419 383737 - Fix edit connection
  app/views/moves/_moved_connection_form.html.erb
  app/views/moves_project_steps/frame.html.erb
Labels: bug

#423 383737 - Add User association to MovesProject
  app/components/page/heading_show_component.rb
  app/controllers/moves_projects_controller.rb
  app/models/moves_project.rb
  app/views/moves/index.html.erb
  app/views/moves_projects/index.html.erb
  app/views/moves_projects/show.html.erb
  config/locales/activerecord.en.yml
  config/locales/activerecord.fr.yml
  db/migrate/20250613132815_add_user_association_to_move_project.rb
  db/schema.rb
  spec/models/moves_project_spec.rb
  spec/requests/moves_projects_controller_request_spec.rb
Labels: enhancement

#390 Modele model cleans up
  app/controllers/modeles_controller.rb
  app/views/modeles/show.html.erb
Labels: bug, enhancement

#424 383737 - Add prev_position to Moves
  app/controllers/moves_controller.rb
  app/helpers/servers_helper.rb
  app/models/bay.rb
  app/models/move.rb
  app/views/moves/_form.html.erb
  app/views/moves/index.html.erb
  app/views/moves_projects/show.html.erb
  config/locales/activerecord.en.yml
  config/locales/activerecord.fr.yml
  config/locales/en.yml
  config/locales/fr.yml
  db/migrate/20250613160706_add_prev_position_to_moves.rb
  db/schema.rb
  spec/models/move_spec.rb
  spec/requests/bays_request_spec.rb
  spec/requests/moves_controller_request_spec.rb
  spec/requests/servers_request_spec.rb
  test/fixtures/moves.yml
Labels: enhancement
