Repository nanego/my-dcim, pull requests merged in 2025-04, with the labels that each got.

#368 Upgrade to ruby 3.4.2
  .github/workflows/tests.yml
  .ruby-version
  Gemfile.lock
Labels: dependencies

#351 Rubocop cleanup
  .rubocop_todo.yml
  app/components/list/table_component.rb
  app/controllers/moves_controller.rb
  app/controllers/ports_controller.rb
  app/controllers/servers_grids_controller.rb
  app/controllers/users_controller.rb
  app/helpers/modeles_helper.rb
  app/helpers/rooms_helper.rb
  app/helpers/servers_helper.rb
  app/models/card.rb
  app/models/frame.rb
  app/models/modele.rb
  app/models/port.rb
  app/models/server.rb
  app/models/servers_grid.rb
  app/services/glpi_client.rb
  app/services/import_equipment_by_csv.rb
  lib/tasks/convert_activities_to_changelog_entries.rake
  lib/tasks/fix_duplicated_slots.rake
  lib/tasks/update_position_by_name.rake
  spec/components/previews/form_errors_component_preview.rb
  spec/requests/servers_request_spec.rb
Labels: quality

#369 342607 - Remove CSS class striped
  app/assets/stylesheets/application.scss
Labels: enhancement

#370 Rubocop cleanups
  .rubocop_todo.yml
  app/controllers/application_controller.rb
  app/controllers/rooms_controller.rb
  app/controllers/servers_controller.rb
  app/controllers/servers_grids_controller.rb
  app/controllers/users/registrations_controller.rb
  app/helpers/servers_helper.rb
  app/models/card.rb
  app/models/connection.rb
  app/models/frame.rb
  app/models/move.rb
  app/models/moved_connection.rb
  app/models/pdu.rb
  app/models/port.rb
  app/models/server.rb
  app/queries/frames/including_servers_query.rb
  app/services/glpi_client.rb
  lib/tasks/update_pdu_lines.rake
  spec/support/omniauth.rb
Labels: quality
