Repository nanego/my-dcim, pull requests merged in 2025-05, with the labels that each got.

#323 367812 - User selects columns to display on Index
  app/components/columns_preferences_dropdown_component.rb
  app/components/list/data_table_component.rb
  app/controllers/bays_controller.rb
  app/controllers/concerns/columns_preferences.rb
  app/controllers/servers_controller.rb
  app/models/processor_filter.rb
  app/processors/bays_processor.rb
  app/processors/servers_processor.rb
  app/views/bays/index.html.erb
  app/views/frames/show.html.erb
  app/views/servers/index.html.erb
  config/locales/activerecord.en.yml
  config/locales/activerecord.fr.yml
  config/locales/components.en.yml
  config/locales/components.fr.yml
  config/locales/en.yml
  config/locales/fr.yml
  spec/components/columns_preferences_dropdown_component_spec.rb
  spec/components/previews/columns_preferences_dropdown_component_preview.rb
  spec/requests/bays_request_spec.rb
  spec/requests/servers_request_spec.rb
  spec/support/request.rb
  spec/support/shared_examples/requests/columns_preferences.rb
  test/models/frame_test.rb
Labels: enhancement

#391 382772 fix 500 on pdu show
  app/components/list/data_table_component.rb
  app/models/breadcrumb.rb
  app/views/power_distribution_units/_form.html.erb
  app/views/power_distribution_units/show.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  spec/support/i18n.rb
Labels: bug, enhancement

#394 Install Hotwire LiveReload
  Gemfile
  Gemfile.lock
Labels: enhancement, quality

#387 Global search with alpha sort
  Gemfile
  Gemfile.lock
  app/controllers/search_controller.rb
  app/models/frame.rb
  app/models/server.rb
  app/models/server_frame_view.rb
  app/views/search/index.html.erb
  db/migrate/20250507150024_create_servers_frames_view.rb
  db/schema.rb
  db/views/servers_frames_view_v01.sql
  spec/requests/search_request_spec.rb
Labels: enhancement
