Repository nanego/my-dcim, pull requests merged in 2025-01, with the labels that each got.

#307 Merge Cables and Connections indexes
  app/assets/stylesheets/application.scss
  app/controllers/cables_controller.rb
  app/controllers/connections_controller.rb
  app/decorators/bay_decorator.rb
  app/decorators/cable_decorator.rb
  app/decorators/port_type_decorator.rb
  app/helpers/servers_helper.rb
  app/models/cable.rb
  app/models/connection.rb
  app/models/filter.rb
  app/processors/cables_processor.rb
  app/processors/connections_processor.rb
  app/views/cables/index.html.erb
  app/views/connections/_form.html.erb
  app/views/connections/edit.html.erb
  app/views/connections/index.html.erb
  app/views/layouts/_sidebar.html.erb
  app/views/servers/show.html.erb
  config/locales/activerecord.fr.yml
  config/locales/en.yml
  config/locales/fr.yml
  config/routes.rb
  db/migrate/20250109174008_revert_add_counter_cache_to_cables.rb
  db/schema.rb
  spec/decorators/bay_decorator_spec.rb
  spec/decorators/cable_decorator_spec.rb
  spec/decorators/port_type_decorator_spec.rb
  spec/models/cable_spec.rb
  spec/processors/cables_processor_spec.rb
  spec/requests/cables_request_spec.rb
  spec/requests/connections_request_spec.rb
  spec/support/decorator.rb
Labels: enhancement

#302 Update dependencies
  .github/workflows/tests.yml
  .ruby-version
  Gemfile
  Gemfile.lock
  app/controllers/visualization/infrastructures_controller.rb
  app/decorators/cable_decorator.rb
  app/models/changelog_entry.rb
  app/models/processor_filter.rb
  spec/models/server_spec.rb
Labels: dependencies

#313 362832 - Create a Modele block on Server pages
  app/views/servers/_form.html.erb
  app/views/servers/show.html.erb
Labels: enhancement

#317 Rubocop cleanup
  .rubocop_todo.yml
  app/controllers/architectures_controller.rb
  app/controllers/bays_controller.rb
  app/controllers/cables_controller.rb
  app/controllers/card_types_controller.rb
  app/controllers/categories_controller.rb
  app/controllers/colors_controller.rb
  app/controllers/disk_types_controller.rb
  app/controllers/disks_controller.rb
  app/controllers/documents_controller.rb
  app/controllers/domaines_controller.rb
  app/controllers/external_app_records_controller.rb
  app/controllers/gestions_controller.rb
  app/controllers/islets_controller.rb
  app/controllers/manufacturers_controller.rb
  app/controllers/memory_components_controller.rb
  app/controllers/memory_types_controller.rb
  app/controllers/modeles_controller.rb
  app/controllers/moves_controller.rb
  app/controllers/port_types_controller.rb
  app/controllers/server_states_controller.rb
  app/controllers/servers_controller.rb
  app/controllers/servers_grids_controller.rb
  app/controllers/sites_controller.rb
  app/controllers/stacks_controller.rb
  app/controllers/visualization/frames_controller.rb
  app/helpers/servers_helper.rb
  app/models/bay.rb
  app/models/composant.rb
  app/models/disk_type.rb
  app/models/external_app_request.rb
  app/models/frame.rb
  app/models/modele.rb
  app/models/port.rb
  app/models/room.rb
  app/models/server.rb
  app/models/user.rb
  app/queries/frames/including_servers_query.rb
  config/initializers/devise.rb
  config/routes.rb
  db/migrate/20160101134143_create_activities.rb
  db/migrate/20160318101235_create_connections.rb
  db/migrate/20160318103009_create_ports.rb
  db/migrate/20160411154022_init_coupled_baies.rb
  db/migrate/20160713084337_create_friendly_id_slugs.rb
  db/migrate/20170626123240_add_missing_indexes.rb
  db/migrate/20170803153658_create_connections_from_ports.rb
  db/migrate/20180110152701_add_attributes_to_servers.rb
  db/migrate/20181203150745_create_active_storage_tables.active_storage.rb
  db/migrate/20230208144748_create_active_storage_variant_records.active_storage.rb
  db/migrate/20231004123921_create_changelog_entries.rb
  lib/tasks/fix_duplicated_slots.rake
  lib/tasks/init_pdus.rake
  lib/tasks/update_pdu_lines.rake
  lib/tasks/update_position_by_name.rake
  spec/models/user_spec.rb
  spec/processors/cables_processor_spec.rb
  spec/requests/servers_request_spec.rb
Labels: quality

#277 Rails 8.0 upgrade
  Gemfile
  Gemfile.lock
  app/controllers/air_conditioners_controller.rb
  app/controllers/architectures_controller.rb
  app/controllers/bays_controller.rb
  app/controllers/card_types_controller.rb
  app/controllers/categories_controller.rb
  app/controllers/clusters_controller.rb
  app/controllers/colors_controller.rb
  app/controllers/contact_assignments_controller.rb
  app/controllers/contact_roles_controller.rb
  app/controllers/contacts_controller.rb
  app/controllers/disk_types_controller.rb
  app/controllers/disks_controller.rb
  app/controllers/documents_controller.rb
  app/controllers/domaines_controller.rb
  app/controllers/frames_controller.rb
  app/controllers/gestions_controller.rb
  app/controllers/islets_controller.rb
  app/controllers/manufacturers_controller.rb
  app/controllers/memory_components_controller.rb
  app/controllers/memory_types_controller.rb
  app/controllers/modeles_controller.rb
  app/controllers/moves_controller.rb
  app/controllers/port_types_controller.rb
  app/controllers/rooms_controller.rb
  app/controllers/server_states_controller.rb
  app/controllers/servers_controller.rb
  app/controllers/sites_controller.rb
  app/controllers/stacks_controller.rb
  app/controllers/users/settings_controller.rb
  app/controllers/users_controller.rb
  app/services/glpi_client.rb
  bin/brakeman
  bin/setup
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/cors.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/new_framework_defaults_8_0.rb
  config/puma.rb
  public/400.html
  public/404.html
  public/406-unsupported-browser.html
  public/422.html
  public/500.html
  public/icon.png
  public/icon.svg
  spec/rails_helper.rb
Labels: enhancement, dependencies

#314 362833 Add exploitation block on server show and form
  app/assets/stylesheets/application.scss
  app/views/layouts/_sidebar.html.erb
  app/views/servers/_form.html.erb
  app/views/servers/show.html.erb
Labels: enhancement

#311 362827 - Add new blocks to show pages
  app/views/air_conditioners/_form.html.erb
  app/views/air_conditioners/show.html.erb
  app/views/architectures/_form.html.erb
  app/views/architectures/show.html.erb
  app/views/bays/_form.html.erb
  app/views/bays/show.html.erb
  app/views/card_types/_form.html.erb
  app/views/card_types/show.html.erb
  app/views/categories/_form.html.erb
  app/views/categories/show.html.erb
  app/views/clusters/_form.html.erb
  app/views/clusters/show.html.erb
  app/views/colors/_form.html.erb
  app/views/colors/show.html.erb
  app/views/contact_assignments/_form.html.erb
  app/views/contact_assignments/show.html.erb
  app/views/contact_roles/_form.html.erb
  app/views/contact_roles/show.html.erb
  app/views/contacts/_form.html.erb
  app/views/contacts/show.html.erb
  app/views/disk_types/_form.html.erb
  app/views/disk_types/show.html.erb
  app/views/domaines/_form.html.erb
  app/views/domaines/show.html.erb
  app/views/frames/_form.html.erb
  app/views/frames/show.html.erb
  app/views/gestions/_form.html.erb
  app/views/gestions/show.html.erb
  app/views/islets/_form.html.erb
  app/views/islets/show.html.erb
  app/views/manufacturers/_form.html.erb
  app/views/manufacturers/show.html.erb
  app/views/memory_types/_form.html.erb
  app/views/memory_types/show.html.erb
  app/views/modeles/_form.html.erb
  app/views/modeles/show.html.erb
  app/views/port_types/_form.html.erb
  app/views/port_types/show.html.erb
  app/views/rooms/_form.html.erb
  app/views/rooms/show.html.erb
  app/views/servers/_form.html.erb
  app/views/servers/show.html.erb
  app/views/sites/_form.html.erb
  app/views/sites/show.html.erb
  app/views/stacks/_form.html.erb
  app/views/stacks/show.html.erb
  config/locales/en.yml
  config/locales/fr.yml
Labels: enhancement

#318 fix: update _params controller method with nested params
  app/controllers/modeles_controller.rb
  app/controllers/servers_controller.rb
  app/controllers/sites_controller.rb
  spec/requests/servers_request_spec.rb
Labels: bug

#319 Fix GlpiClient
  app/services/glpi_client.rb
Labels: bug

#315 360356 - Make port with unnamed cable have color and type drawn
  app/components/list/table_component.rb
  app/decorators/cable_decorator.rb
  app/views/cables/index.html.erb
  app/views/categories/index.html.erb
  app/views/external_app_records/index.html.erb
  app/views/rooms/index.html.erb
  spec/components/list/table_component_spec.rb
  spec/decorators/cable_decorator_spec.rb
Labels: enhancement
