Repository nanego/my-dcim, pull requests merged in 2025-02, with the labels that each got.

#321 367304 - Fixing ActiveModel::ForbiddenAttributesError on Servers#sort
  app/controllers/servers_controller.rb
Labels: bug

#322 Rubocop cleanup
  .rubocop_todo.yml
  Gemfile.lock
  app/controllers/connections_controller.rb
  app/controllers/servers_controller.rb
  app/controllers/servers_grids_controller.rb
  app/controllers/users/sessions_controller.rb
  app/helpers/modeles_helper.rb
  app/helpers/servers_helper.rb
  app/models/card.rb
  app/models/frame.rb
  app/models/move.rb
  app/models/server.rb
  app/models/user.rb
  app/processors/concerns/sortable.rb
  app/services/import_equipment_by_csv.rb
  config/environments/production.rb
  lib/omniauth/dynamic_full_host.rb
  lib/tasks/convert_activities_to_changelog_entries.rake
  lib/tasks/update_pdu_lines.rake
  spec/models/server_spec.rb
  spec/support/shared_examples/models/changelogable.rb
  test/fixtures/servers.yml
  test/services/omniauth_dynamic_full_host_test.rb
Labels: quality

#327 Rubocop cleanup
  .rubocop_todo.yml
  app/components/list/data_table_component.rb
  app/controllers/modeles_controller.rb
  app/controllers/moves_controller.rb
  app/models/frame.rb
  app/services/glpi_client.rb
  config/initializers/field_with_errors.rb
  db/migrate/20180110152701_add_attributes_to_servers.rb
  spec/components/previews/card_component_preview.rb
Labels: quality

#320 363399 - Fixing port position not displaying when 1FC
  app/helpers/servers_helper.rb
Labels: bug

#331 368493 - Fixing 500 on Connections#edit
  app/controllers/connections_controller.rb
Labels: bug

#325 366659 - Add server type filter
  app/controllers/servers_controller.rb
  app/processors/servers_processor.rb
  app/views/servers/index.html.erb
  config/locales/activerecord.en.yml
  config/locales/activerecord.fr.yml
  spec/processors/servers_processor_spec.rb
Labels: enhancement

#336 362850 - Update all equipments model locales
  app/controllers/concerns/.keep
  app/views/air_conditioners/edit.html.erb
  app/views/air_conditioners/index.html.erb
  app/views/air_conditioners/new.html.erb
  app/views/air_conditioners/show.html.erb
  app/views/bays/index.html.erb
  app/views/clusters/show.html.erb
  app/views/domaines/show.html.erb
  app/views/external_app_records/index.html.erb
  app/views/external_app_records/settings.html.erb
  app/views/frames/show.html.erb
  app/views/gestions/show.html.erb
  app/views/layouts/_sidebar.html.erb
  app/views/layouts/navigation/_devices_dropdown.html.erb
  app/views/modeles/index.html.erb
  app/views/modeles/show.html.erb
  app/views/power_distribution_units/_form.html.erb
  app/views/power_distribution_units/show.html.erb
  app/views/servers/_form.html.erb
  app/views/servers/duplicate.html.erb
  app/views/servers/edit.html.erb
  app/views/servers/import_csv.html.erb
  app/views/servers/index.html.erb
  app/views/servers/new.html.erb
  app/views/servers/show.html.erb
  app/views/stacks/show.html.erb
  config/locales/activerecord.en.yml
  config/locales/activerecord.fr.yml
  config/locales/en.yml
  config/locales/fr.yml
  spec/components/previews/has_many_turbo_frame_component_preview.rb
  spec/requests/users_request_spec.rb
  spec/requests/visualization/infrastructure_request_spec.rb
  spec/requests/visualization/network_capacity_request_spec.rb
  spec/support/shared_examples/authentication.rb
  test/fixtures/users.yml
Labels: enhancement

#338 370392 - Fix 500 on sort options (external app records + bays)
  app/processors/external_app_records_processor.rb
  app/views/bays/index.html.erb
  app/views/external_app_records/index.html.erb
Labels: bug

#324 Add information to Moves#index first table
  app/views/moves/_form.html.erb
  app/views/moves/edit.html.erb
  app/views/moves/index.html.erb
  config/locales/activerecord.en.yml
  config/locales/activerecord.fr.yml
  config/locales/en.yml
  config/locales/fr.yml
  spec/components/form/actions_component_spec.rb
  spec/components/page/heading_component_spec.rb
  spec/components/page/heading_edit_component_spec.rb
  spec/components/page/heading_new_component_spec.rb
  spec/components/page/heading_show_component_spec.rb
Labels: enhancement

#326 367616 - Add overview block to site room and islet
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/rooms.css.scss
  app/components/label_component.rb
  app/decorators/islet_decorator.rb
  app/views/bays/_overview.html.erb
  app/views/islets/show.html.erb
  app/views/rooms/_room_overview.html.erb
  app/views/rooms/overview.html.erb
  app/views/rooms/show.html.erb
  app/views/sites/show.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  spec/components/label_component_spec.rb
  spec/decorators/islet_decorator_spec.rb
Labels: enhancement

#329 Rubocop cleanup
  .rubocop_todo.yml
  app/components/list/table_component.rb
  app/controllers/frames_controller.rb
  app/controllers/moves_controller.rb
  app/helpers/modeles_helper.rb
  app/helpers/servers_helper.rb
  app/models/cluster.rb
  app/models/frame.rb
  app/models/port.rb
  app/models/server.rb
  app/models/user.rb
  db/migrate/20240207105229_add_counter_caches.rb
  db/migrate/20250212105637_add_uniq_index_on_numero_to_servers.rb
  db/schema.rb
  spec/components/list/data_table_component_spec.rb
  spec/components/previews/list/data_table_component_preview.rb
  test/models/move_test.rb
  test/services/glpi_client_test.rb
Labels: quality

#345 342607 - Remove unused islet Method from RoomsController
  app/controllers/rooms_controller.rb
Labels: enhancement

#341 Fix processors with joins
  Gemfile.lock
  app/controllers/air_conditioners_controller.rb
  app/controllers/bays_controller.rb
  app/controllers/cables_controller.rb
  app/controllers/clusters_controller.rb
  app/controllers/contact_assignments_controller.rb
  app/controllers/frames_controller.rb
  app/controllers/islets_controller.rb
  app/controllers/modeles_controller.rb
  app/controllers/rooms_controller.rb
  app/controllers/servers_controller.rb
  app/processors/air_conditioners_processor.rb
  app/processors/bays_processor.rb
  app/processors/external_app_records_processor.rb
  app/processors/frames_processor.rb
  app/processors/islets_processor.rb
  app/processors/servers_processor.rb
  app/views/bays/index.html.erb
  app/views/external_app_records/index.html.erb
  spec/processors/air_conditioners_processor_spec.rb
  spec/processors/bays_processor_spec.rb
  spec/processors/cables_processor_spec.rb
  spec/processors/card_types_processor_spec.rb
  spec/processors/clusters_processor_spec.rb
  spec/processors/contact_assignments_processor_spec.rb
  spec/processors/external_app_records_processor_spec.rb
  spec/processors/frames_processor_spec.rb
  spec/processors/islets_processor_spec.rb
  spec/processors/modeles_processor_spec.rb
  spec/processors/rooms_processor_spec.rb
  spec/processors/servers_processor_spec.rb
Labels: bug, enhancement

#348 Reset locale between tests
  spec/components/changelog_entries/object_list_component_spec.rb
  spec/components/filter_component_spec.rb
  spec/components/form/actions_component_spec.rb
  spec/components/form_errors_component_spec.rb
  spec/components/has_many_turbo_frame_component_spec.rb
  spec/components/page/heading_component_spec.rb
  spec/components/page/heading_edit_component_spec.rb
  spec/components/page/heading_new_component_spec.rb
  spec/components/page/heading_show_component_spec.rb
  spec/decorators/cable_decorator_spec.rb
  spec/requests/users/settings_request_spec.rb
  spec/requests/users_request_spec.rb
  spec/requests/visualization/infrastructure_request_spec.rb
  spec/requests/visualization/network_capacity_request_spec.rb
  spec/support/i18n.rb
  spec/support/shared_examples/authentication.rb
  test/fixtures/users.yml
Labels: enhancement

#347 342607 - Remove Moves#show.html action
  app/controllers/moves_controller.rb
  app/views/moves/show.html.erb
  config/routes.rb
  spec/requests/moves_request_spec.rb
  test/controllers/moves_controller_test.rb
Labels: enhancement
