Repository nanego/my-dcim, pull requests merged in 2025-08, with the labels that each got.

#458 Update dependencies
  Gemfile.lock
  app/controllers/colors_controller.rb
  app/models/card_type.rb
  app/models/frame.rb
  app/models/modele.rb
  app/models/port.rb
  app/models/room.rb
  app/models/server.rb
  app/models/servers_grid.rb
  app/processors/air_conditioners_processor.rb
  app/processors/bays_processor.rb
  app/processors/cables_processor.rb
  app/processors/card_types_processor.rb
  app/processors/categories_processor.rb
  app/processors/clusters_processor.rb
  app/processors/contact_assignments_processor.rb
  app/processors/contact_roles_processor.rb
  app/processors/contacts_processor.rb
  app/processors/external_app_records_processor.rb
  app/processors/frames_processor.rb
  app/processors/islets_processor.rb
  app/processors/modeles_processor.rb
  app/processors/rooms_processor.rb
  app/processors/servers_processor.rb
  app/processors/users_processor.rb
  test/services/omniauth_dynamic_full_host_test.rb
Labels: dependencies

#465 Update user_to_role badge component to include admin one
  app/decorators/user_decorator.rb
  app/views/users/index.html.erb
  app/views/users/show.html.erb
  spec/decorators/user_decorator_spec.rb
Labels: enhancement

#466 Code cleanup
  app/controllers/concerns/authorization.rb
  app/controllers/external_app_records_controller.rb
  app/controllers/servers_controller.rb
  app/views/servers/grid.html.erb
  config/routes.rb
Labels: quality

#475 Fix servers_moves_for_frame_at_current_step for move happening in the same frame
  app/models/moves_project_step.rb
  spec/models/moves_project_step_spec.rb
  test/fixtures/moves.yml
  test/fixtures/moves_project_steps.yml
  test/fixtures/moves_projects.yml
Labels: bug
